version: '3.8'

services:
#   survey-app:
#     build: .
#     container_name: survey-app
#     restart: unless-stopped
#     environment:
#       - NODE_ENV=production
#       - DATABASE_URL=postgresql://postgres:postgres123@survey-db:5432/survey_db
#       - PORT=3000
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres
#     networks:
#       - survey-network
  postgres:
    image: postgres:15
    container_name: survey-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: survey_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - survey-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: survey-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@survey.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
      - metabase-db
    networks:
      - survey-network

  metabase-db:
    image: postgres:15
    container_name: metabase-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
    ports:
      - "5433:5432"
    volumes:
      - metabase-db-data:/var/lib/postgresql/data
    networks:
      - survey-network

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: metabase-db
    depends_on:
      - metabase-db
    networks:
      - survey-network

networks:
  survey-network:
    driver: bridge

volumes:
  postgres-data:
  metabase-db-data: